require 'spec/rake/spectask'

task :default => :spec

if !defined?(Spec)
  puts "spec targets require RSpec"
else
  desc "Run integration tests"
  Spec::Rake::SpecTask.new('spec') do |t|
    t.spec_files = FileList['spec/app_spec.rb']
    t.spec_opts = ['-cfs']
  end

  desc "Run full test suite"
   Spec::Rake::SpecTask.new('spec:full') do |t|
    t.spec_files = FileList['spec/*_spec.rb']
    t.spec_opts = ['-cfs']
  end
end
